name:                clam-bot
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

description: clam

dependencies:
- base
- lens
- calamity
- dhall
- relude

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedLabels
- OverloadedLists
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- UnicodeSyntax

library:
  source-dirs: src

executables:
  clam-bot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - clam-bot

tests:
  clam-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clam-bot
