name:                clam-bot
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

description: clam

dependencies:
- base
- bytestring
- calamity
- dhall
- di
- di-polysemy
- emojis
- http-api-data
- lens
- monad-logger
- path-pieces
- persistent
- persistent-postgresql
- persistent-template
- polysemy
- polysemy-plugin
- relude
- resource-pool
- text
- time

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLabels
- OverloadedLists
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- UnicodeSyntax

executables:
  clam-bot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wno-unused-do-bind
    - -fplugin=Polysemy.Plugin

tests:
  clam-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clam-bot
